/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppSubscriptionsRouteImport } from './routes/app/subscriptions'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSessionsRouteImport } from './routes/app/sessions'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppRecordsRouteImport } from './routes/app/records'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppPatientsRouteImport } from './routes/app/patients'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'

const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/app/subscriptions',
  path: '/app/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/app/sessions',
  path: '/app/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/app/records',
  path: '/app/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/app/payments',
  path: '/app/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/app/patients',
  path: '/app/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app/dashboard': typeof AppDashboardRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesByTo {
  '/app/dashboard': typeof AppDashboardRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app/dashboard': typeof AppDashboardRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sessions': typeof AppSessionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app/dashboard'
    | '/app/patients'
    | '/app/payments'
    | '/app/profile'
    | '/app/records'
    | '/app/reports'
    | '/app/sessions'
    | '/app/settings'
    | '/app/subscriptions'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/dashboard'
    | '/app/patients'
    | '/app/payments'
    | '/app/profile'
    | '/app/records'
    | '/app/reports'
    | '/app/sessions'
    | '/app/settings'
    | '/app/subscriptions'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/app/dashboard'
    | '/app/patients'
    | '/app/payments'
    | '/app/profile'
    | '/app/records'
    | '/app/reports'
    | '/app/sessions'
    | '/app/settings'
    | '/app/subscriptions'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/app/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sessions': {
      id: '/app/sessions'
      path: '/app/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/records': {
      id: '/app/records'
      path: '/app/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/app/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/app/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
